allowBuilds:
  '@firebase/util': set this to true or false
  '@sveltejs/kit': set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  svelte-preprocess: set this to true or false
